### PR TITLE
fix for #400

### PR DESCRIPTION
**Pull request by DWMiller**

### CODE REVIEW

**Comment by ryan-roemer** [comment]
Thanks for the PR @DWMiller !

If you get a chance can you:

- [ ] Fix the lint errors? (We check for the following stuff: https://github.com/FormidableLabs/nuka-carousel/blob/master/CONTRIBUTING.md#tests)
- [ ] Add a regression test that this change fixes?

Thanks!!!

**Comment by DWMiller** [comment]
Not likely, this was just a quick inline edit on github, if it's inadequate feel free to toss it.

**Comment by ryan-roemer** [comment]
Understood if you don't have time.

We'll wait on this one until someone from the community or us finds some time to get it into mergeable shape and just use it for guidance in the meantime.

/cc @boygirl

**Comment by pho3nixf1re** [comment]
Looks like #403 has the required test. This is a pretty big bug that is a total blocker for me requiring a downgrade.

**Comment by sarmeyer** [comment]
fixed in #403 - merged and released

**Pull request closed without merging**
