### PR TITLE
Add callback `onSlideChange`

### PR DESCRIPTION
**Pull request by ruscoder**
A added useful callback to `onSlideChange` prop.

Usage:

```
onSlideChange: function (currentSlide) {
  ...
}
...

<Carousel onSlideChange={this.onSlideChange}>
...
</Carousel>
```

### CODE REVIEW

**Comment by eriklharper** [comment]
+1

**Comment by eriklharper** [comment]
@ruscoder you should add the changed lines to the `goToSlide` method as well on this line: https://github.com/kenwheeler/nuka-carousel/pull/33/files#diff-3b3282d4ffc50855fd21a0660d26ff97L359

**Comment by sh3nan1gans** [comment]
+1 - would love to have this merged in

**Comment by reel** [comment]
+1

**Comment by agroves333** [comment]
+1 Yes!

**Comment by djkirby** [comment]
I believe the `afterSlide` callback takes care of this now.

**Comment by agroves333** [comment]
Yes. Refer to https://github.com/kenwheeler/nuka-carousel/pull/42

**Comment by mariano-formidable** [comment]
The current build of `nuka-carousel` (4.3.2) has `beforeSlide` and `afterSlide` callbacks that address feature this PR added.

**Pull request closed without merging**
