### PR TITLE
Cut down object creation during transitions

### PR DESCRIPTION
**Pull request by sghall**
Hey,  author of react-move here.  Just happen to see https://github.com/FormidableLabs/nuka-carousel/issues/318.  I think this might help.  If I understand correctly, these objects just need to be created once per render of the carousel.  Inside the children function of Animate these objects are being created on each frame of the animation.  I did run the tests on this and everything passed.

### CODE REVIEW

**Comment by carlospaelinck** [comment]
@sghall Thank you, this is a great optimization.

**Comment by ryan-roemer** [comment]
Fantastic work @sghall ! Thanks!

_Side note_ -- Our lint isn't working due to the `prettier` extends in eslintrc disabling a whole ton of things without us having something actually "fix" per prettier. will fix in follow on workl

**Comment by sghall** [comment]
Right on.  Glad to help out!

**Comment by ryan-roemer** [comment]
Released in `nuka-carousel@4.0.3`

**Pull request merged**
