### PR TITLE
Prevent multiple afterSlide calls of which some used undefined variabes, breaking slide-changes

### PR DESCRIPTION
**Pull request by pimverlangen**
### Description

After upgrading Nuka Carousel to 4.4.4, our `afterSlide` callbacks were being called twice and with `slideIndex === NaN`. After quickly checking, it seemed that the library tries to call `props.slideCount`, but `slideCount` is not a prop of the component. Further investigating, seemed that the before/after callbacks seemed to be best placed in the `goToSlide` function, so that's what this PR also includes (`afterSlide` is not used outside of this function anymore).

#### Type of Change

- [X] Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

Switching slides and adding a console.log to the `afterSlide` prop to see how often it gets called and with what value. Then debugged it down some more to come to the fixes in this PR.

### Checklist: 

- [X] My code follows the style guidelines of this project (I have run `yarn lint`)
- [x] New and existing unit tests pass locally with my changes (I have run `yarn test` and `yarn test-e2e`)
- [X] I have performed a self-review of my own code
- [X] My changes generate no new warnings

### CODE REVIEW

**Comment by wenJonSnow** [comment]
How to solve this problem?

**Comment by wenJonSnow** [comment]
I have encountered this problem. How can I solve it?

**Comment by sjfkai** [comment]
> I have encountered this problem. How can I solve it?

@wenJonSnow  You can try to use the previous version, like v4.4.1.

**Comment by wenJonSnow** [comment]
@sjfkai  Thank you, but version 4.4.1 will shake the page when it slides.

**Comment by fi3ework** [comment]
please merge this

**Comment by sarmeyer** [comment]
Will have this in a release by the end of the week

**Pull request merged**
