### PR TITLE
use relative positioning instead of absolute

### PR DESCRIPTION
**Pull request by fat**
I kept running into some weird issues with height not getting calculated quite right… And was wondering if you tried using position relative rather then absolute?

I noticed in an issue you mentioned that you used absolute for wrap around… but I switched up the math a bit and this seems to be working in demo (with wraparound and relative)

Unfortunately i couldn't get the tests running (so i may have totally broke everything :P)

If nothing else, thought it might be casually interesting to you.

thanks for the cool lib 🏄

### CODE REVIEW

**Comment by kenwheeler** [comment]
just seeing this now. this looks dope, I'll give it a spin.

**Comment by kenwheeler** [comment]
@mdaxtman can you check this out?

**Comment by mdaxtman** [comment]
This is good, thanks! @fat do you mind rebasing and resolving any conflicts, and running `gulp babel`? Otherwise I can pull locally and do it myself. Up to you. :-)

**Comment by mdaxtman** [comment]
closed in favor of #161

**Pull request closed without merging**
