### PR TITLE
[MINOR] Add props for how the carousel should calculate height

### PR DESCRIPTION
**Pull request by Nehle**
Adds four props to how the carousel should calculate the height. `first` , `max` or `current`, as well as a prop that indicates whether the height needs to be recalculated on update. Based on PR #279 

cc @ryan-roemer @kenwheeler @ajoshi0

### CODE REVIEW

**Comment by ajoshi0** [comment]
@ryan-roemer can we get this merged please

**Comment by ryan-roemer** [comment]
@carlospaelinck -- Can you advise these fine folks on next steps and/or merge this? I'm not up to speed 😄

**Comment by tchon** [comment]
Any updates here? Thanks.

**Comment by ryan-roemer** [comment]
It's the weekend @tchon 😄 

Carlos has put in a ton of time here and we can pick up the discussion on Monday (assuming he's offline until then).

**Comment by ryan-roemer** [comment]
Released in `nuka-carousel@3.1.0` from `3.x` legacy branch.

@Nehle -- I think we're ready for a port of this to `master` (aka v4.x current) branch after https://github.com/FormidableLabs/nuka-carousel/pull/293 lands.

**Pull request merged**
