### PR TITLE
fix: filter out null slides

### LINKED ISSUE #951: Empty slide rendered with false conditional
# Bugs and Questions

### Describe Your Environment

- What version of nuka-carousel are you using?
5.2.0
- What version of React are you using?
18.2.0
- What browser are you using?
Brave

### Describe the Problem

When having a slide that should be conditionally rendered, if false an empty slide is rendered instead of none.

Code sandbox reproduction: https://codesandbox.io/s/heuristic-stonebraker-3pn8jc?file=/src/App.js:233-383

**Expected behavior:** 
Not having the empty slide when a condition is false

**Actual behavior:**
Empty slide being rendered.

### PR DESCRIPTION
**Pull request by ValGeorgiev**
### Description
When there is a condition to not render a particular slide, the library is rendering an empty slide. We need to filter out the null  slides.

Fixes #951 

#### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)

### Checklist

- [ ] My code follows the style guidelines of this project (I have run `pnpm run lint`)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes (I have run `pnpm run test:ci-with-server`/`pnpm run test`)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by fritz-c** [comment]
This PR seems like a good candidate to add some tests. I've got a WIP branch to fix the autoplay timing that introduces some integration tests using react-testing-library. If you don't mind waiting for that to get finished up and merged, maybe you can use that as a base for a simple integration test or two that makes sure slides are not rendered for null children.

**Review by fritz-c — CHANGES_REQUESTED** [review]
You'll need to add a changeset file with `pnpm changeset`. I'll add that to the PR template checklist soon.

**Review by fritz-c — APPROVED** [review]

**Review by gksander — APPROVED** [review]
👍

**Review by buchansm — APPROVED** [review]
Nice, thanks for adding `slideCount`! 🙌

**Pull request merged**
