### PR TITLE
Scroll3D Transition Mode

### PR DESCRIPTION
**Pull request by juanmardefago**
### Description

Added a new transition mode for the carousel, using the scroll as a base template.
The new transition mode is called "scroll3d", which creates kind of a layered 3d effect.

#### Type of Change

- [x] New feature (non-breaking change which adds functionality)

### How Has This Been Tested?

It's been manually tested with some configurations.

It has a lot of unit test done to the core functions of the transition mode.

### CODE REVIEW

**Comment by juanmardefago** [comment]
Changed PR to WIP since i'm having to do some small modifications and will be adding tests.

**Comment by juanmardefago** [comment]
@thisJJ I've added tests and updated the README.md, I think the PR is ready to be code reviewed again (I only added the tests and 1 fix since the last CR), and merged afterwards.

I'll remove the WIP prefix!

**Comment by sigginet** [comment]
@sarmeyer can you get someone to CR this soon since @thisJJ is on vacation? 😇

**Comment by sarmeyer** [comment]
@sigginet yes I'll look at it today

**Comment by sarmeyer** [comment]
looks great! I'll push a release up

**Pull request merged**
