### PR TITLE
Fix wrapAround problem for slidesToShow>1

### LINKED ISSUE #276: wrapAround problem for slidesToShow>1
Thanks for the neat library ! This is the little problem I bumped into. In case you set `slidesToShow` a number bigger than one like `3`, when scrolling back from index `0` in the middle of the way `item0` disappears.

[item0 hides when scrolling back from index0 - recorded](https://gfycat.com/gifs/detail/MassiveFalseBarnswallow)

Minimal sandbox of the problem:

[Edit m57o4yjm89](https://codesandbox.io/s/m57o4yjm89)

### PR DESCRIPTION
**Pull request by nimatrueway**
Fixes #276

### CODE REVIEW

**Comment by regan-karlewicz** [comment]
Someone should merge this!

**Comment by nimatrueway** [comment]
@ryan-roemer This is a clear, stright-forward bug that has been reproduced in the issue and is fixed with modification of a single line of code. Please prioritize this MR.

**Comment by ryan-roemer** [comment]
@kenwheeler - can you take a look at this small change and verify? Thanks!!!

**Comment by regan-karlewicz** [comment]
@ryan-roemer I would really appreciate this being merged! I had to pull it out of node_modules and edit it myself for it to work. 

I can verify that this fixes the problem.

**Comment by ryan-roemer** [comment]
Can we get a regression unit test added to this PR? Thanks!

(I'm adding travis right now btw, so will require and upstream merge when that lands).

**Pull request closed without merging**
