### PR TITLE
Fix backwards scroll flicker when wrapAround prop is set

### LINKED ISSUE #140: First slide flickering when scrolling backwards.
In the below example, the first slide disappears from the screen when scrolling backwards:
carousel

``` javascript
<Carousel
  autoplay={true}
  cellAlign='center'
  slidesToShow={2}
  cellSpacing={20}
  wrapAround={true}
  slideWidth='400px'
  decorators={[]}>
    <img src="http://placehold.it/1000x400/ffffff/c0392b/&text=slide1"/>
    <img src="http://placehold.it/1000x400/ffffff/c0392b/&text=slide2"/>
    <img src="http://placehold.it/1000x400/ffffff/c0392b/&text=slide3"/>
</Carousel>
```

### PR DESCRIPTION
**Pull request by nowarkdev**
Fixes #140 

When wrapAround property is passed there is a flicker when scrolling backwards from first to last slide. This fixes that.

### CODE REVIEW

**Comment by roryp2** [comment]
That looks good!

**Comment by sakulstra** [comment]
@kenwheeler could someone with repository access look over this? We'd really love to keep using your npm version and not start working with on a fork :(

**Comment by mdaxtman** [comment]
This looks good! Merged!

**Comment by yanivel** [comment]
Nope, still happens

**Comment by maximusnikulin** [comment]
+1

**Comment by sinxwal** [comment]
@nowarkdev Hi!
Why changes in  lib/carousel.js and src/carousel.js do not match?

**Pull request merged**
