### PR TITLE
Feature active class for current state

### PR DESCRIPTION
**Pull request by MMasey**
Adds "active" class to slide when it is the current slide. 

Issue [#122](https://github.com/FormidableLabs/nuka-carousel/issues/112)

### CODE REVIEW

**Comment by mariano-formidable** [comment]
This PR is similar to #85

**Comment by CharlyJazz** [comment]
why this isn't merged yet?

**Comment by ryan-roemer** [comment]
@CharlyJazz -- Because it's way, way out of date from modern `nuka` and has merge conflicts galore. 😉 

Anyone interested -- can someone look at this PR and https://github.com/FormidableLabs/nuka-carousel/pull/85 and give us an opinion as to:

1. Are these PRs still needed?
2. If so, which one is better?
3. ... and then ideally pull a fresh branch off current `master` and create a new PR that has a much better chance of being mergeable...
4. with tests now that we have a robust spec + e2e test infrastructure and test base

Thanks!!!! 🙏 

/cc @sarmeyer @ashika01 @boygirl @mariano-formidable

**Comment by sarmeyer** [comment]
This feature is added in with this PR - https://github.com/FormidableLabs/nuka-carousel/pull/432

**Pull request closed without merging**
