### PR TITLE
Fixed width slides

### LINKED ISSUE #927: Fixed width for slides does not behave responsively
# Bugs and Questions

### Describe Your Environment

- What version of nuka-carousel are you using? 5.1.3
- What version of React are you using? 18.0.0
- What browser are you using? Chrome

### Describe the Problem

https://codesandbox.io/s/brave-wing-6ml10g

**Expected behavior:** Slides should keep their fixed width with consistent spacing in-between when resizing the window. More cards should show as the window gets wider, but cards should always have the same width and spacing.
**Actual behavior:** Slides seem to be flexed and spacing in-between will change to keep slidesToShow consistent. When window is narrow (mobile) slides bundle up and overlap each other.

### Additional Information

In v4, I was able to get this working with slideWidth, which has been deprecated. I have a carousel of fixed width (280px) cards which consistent cell spacing (14px) that the user can click next to scroll through horizontally. There was no need for slidesToShow because the cards just fill up the carousel depending on the width. So if the width of the window is large, more cards are shown. If it's smaller, less cards are shown but they're always 280px wide with 14px spacing. How do I get this behavior on v5?

### PR DESCRIPTION
**Pull request by vaishal**
### Description

Implemented a prop for fixed width slides `slideWidth` and `slidesToScroll="auto"`.

Fixes #927 #979 

#### Todo
- [x] Fix `cellAlign` with new changes

#### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

### Checklist

- [x] My code follows the style guidelines of this project (I have run `pnpm run lint`)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes (I have run `pnpm run test:ci-with-server`/`pnpm run test`)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have recorded any user-facing fixes or changes with `pnpm changeset`.
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by allypalanzi** [comment]
this looks great 👍🏻 will make it so my team can upgrade to v5 finally!

**Comment by F-Moody** [comment]
Hello, any idea when this feature will be released ?

**Comment by ValGeorgiev** [comment]
Note about the cypress test that is failing, tested it locally and everything is working, I am going to push it into the main. Please raise an issue if you see something wrong.

**Comment by allypalanzi** [comment]
this is exciting! will this be released in v5?

**Comment by svanetten1976** [comment]
@vaishal @allypalanzi yes I was also wondering if slidesToScroll auto would work with a fixed slideWidth set. I had been using v4.8.4 in a project that had a requirement of showing a variable number of slides based on the viewport width (but pagin one at a time or smoothly swiping left and right, and 4.8.4 worked great for that). So when I saw that this functionality was added to v5.4.1 I tried to upgrade but the carousel now doesn't work. Am I missing something? Are additional props / config settings that are required for fixed width slides to work? Thanks -- Steve

**Comment by svanetten1976** [comment]
Ah I see what's happening... the patch to allow fixed width slides has been merged into main but not yet made available in a release: https://github.com/FormidableLabs/nuka-carousel/compare/nuka-carousel%405.4.1...main
   Any idea when this will actually be available in a release @ValGeorgiev ? Thanks! -- Steve

**Comment by joekur** [comment]
Hi, I'm also waiting on an updated v5 release with this fix. Particularly because we've encountered a bug in v4, for which it seems more reasonable to make the jump to v5 instead of trying to backport a fix to v4.

It would be nice to confirm at least if Formidable still intends to maintain this package, and what sort of timeline we could expect on this release, to inform if we should be considering forking or other alternatives. Thanks!

**Comment by BrittanyIRL** [comment]
@joekur @allypalanzi @svanetten1976 @F-Moody 

Hi all, just wanted to jump in here to tell you that V5.5.0 was released this past weekend - https://github.com/FormidableLabs/nuka-carousel/releases/tag/5.5.0 and this PR #985 is included in it.

**Comment by svanetten1976** [comment]
@BrittanyIRL that's fantastic! Thanks or letting me know!

**Pull request merged**
