### PR TITLE
Solving chrome to monitor touch class event reporting

### PR DESCRIPTION
**Pull request by BlackHole1**
Reference resources: https://developers.google.com/web/updates/2017/01/scrolling-intervention

image

### CODE REVIEW

**Comment by ryan-roemer** [comment]
@carlospaelinck -- Can you validate this small change if you have a moment?

**Comment by ryan-roemer** [comment]
Released in `nuka-carousel@4.2.3`. 

Thanks @BlackHole1 !

**Comment by BlackHole1** [comment]
I found that my `Pull requests` is wrong!

`touchAction: 'none'` should be in the `getListStyles` function.
I am sorry that I did not check carefully when I submitted.

It should be this: https://github.com/BlackHole1/nuka-carousel/commit/01be133fc9d331da54186ecc63071a0b65fca48a

I'm very sorry....

**Comment by ryan-roemer** [comment]
@BlackHole1 -- can you open a new pr and cc @carlospaelinck ? Thanks!

**Comment by BlackHole1** [comment]
All right. Just a moment, please.

**Comment by BlackHole1** [comment]
And put forward, please verify #366

**Pull request merged**
