### PR TITLE
Fix for #82: fractional values for translate3d cause blurriness

### PR DESCRIPTION
**Pull request by kartikluke**
Fractional values for translate3d cause a blurring effect in most browsers.

### CODE REVIEW

**Comment by kartikluke** [comment]
@kenwheeler I've tested this fix out in production. It's a simple fix that improves the look a lot. Couldn't figure out why the blur was showing up till recently.

**Comment by kartikluke** [comment]
Rebased this on master.

**Comment by kartikluke** [comment]
@kenwheeler Could you review this?

**Comment by wmertens** [comment]
Would it not be better to return a rounded integer from `getTweeningValue` instead?

**Comment by kartikluke** [comment]
Looks like nuka-carousel is no longer using react-tween-state.

**Pull request closed without merging**
