### PR TITLE
Set slideHeight to match tallest slide.

### LINKED ISSUE #126: setDimensions sets height based on first slide
With slides of varying height, the setDimensions should go through all the slide heights. Currently it's just getting firstSlide.offsetHeight. This hides the slides that are taller then the first one as overflow. setDimensions function on Line 639

### PR DESCRIPTION
**Pull request by aij**
heightMode=max matches tallest height ever seen
heightMode=adaptive matches current tallest height

Fixes #126

Separated out from pull #133 .

### CODE REVIEW

**Comment by aij** [comment]
I was going to add some tests too, but now I can't run tests even with a clean checkout of origin/master.

> 03 08 2016 13:14:08.002:INFO [launcher]: Starting browser PhantomJS
> 03 08 2016 13:14:08.354:INFO [PhantomJS 1.9.8 (Linux 0.0.0)]: Connected on socket /#PGT0dJVvxMW1XpisAAAA with id 42029606
> PhantomJS 1.9.8 (Linux 0.0.0) ERROR
>   RangeError: Maximum call stack size exceeded.
>   at /home/aij/tmp/nuka-carousel/node_modules/chai/chai.js:3863
> 
> Finished in 0.145 secs / 0 secs
> 
> SUMMARY:
> ✔ 0 tests completed

Not sure if this is due to a change on my workstation or in the Nondeterministic Package Manager.

Also, upper management may be deciding we don't want a carousel after all, so I'm not sure how much of a priority this will be for me... Figured I should at least send you the cleaner PR.

**Comment by ivan-rudyi-personal** [comment]
Would like to see this MR in master

**Comment by ryan-roemer** [comment]
Is this PR needed now that https://github.com/FormidableLabs/nuka-carousel/pull/291 is merged and released?

**Comment by aij** [comment]
Probably not. That PR seems to include everything we needed.

**Pull request closed without merging**
