### PR TITLE
fixed issue where unable to reach last item(s) with slidesToShow > 1

### PR DESCRIPTION
**Pull request by awhitehouse104**

### CODE REVIEW

**Comment by gkrinc** [comment]
I installed your commit, but the problem from Issue #96 persists :s

**Comment by awhitehouse104** [comment]
Forgot to run the build command, sorry. I've just updated. Hopefully it works for you now.

**Comment by gkrinc** [comment]
It looks like the issue I'm having is actually happening in handleSwipe(e)...this line
```if (
          this.state.currentSlide >= React.Children.count(this.props.children) - slidesToShow &&
          !this.props.wrapAround
        )```

I'm on index 6 with a count of 9 therefore it won't let me slide past index 6

**Comment by awhitehouse104** [comment]
Thanks, yes you were right I needed to apply the same logic to swipe. I updated again, give it another try.

**Comment by gkrinc** [comment]
I made some similar changes, but it gets a little deeper than that...need to handle cellAlign center as well. Likely going to submit a PR myself. Trying to work through all scenarios as we speak.

**Comment by awhitehouse104** [comment]
OK, yeah I noticed a few other issues as well but is it related to this PR or something different?

**Comment by gkrinc** [comment]
Related...

For example your change
```this.state.currentSlide >= (React.Children.count(this.props.children) - 1)```
I did as 
```this.state.currentSlide >= React.Children.count(this.props.children) - (this.props.cellAlign === 'center' ? 1 : slidesToShow) &&```

Trying to handle all Carousel settings like cellAlign, slidesToShow, etc

The last problem I'm having is when you set the slide index to 5 for example and there's 6 slides and cellAlign isn't set with slidesToShow equal to 3, slide 6 is at the far left of the visible frame with 2 empty slides on the right

**Comment by gkrinc** [comment]
Here are my changes

https://github.com/gkrinc/nuka-carousel/commit/0aa1ec16f49e2546b077e0b9af224ebc1c1e48d5

**Comment by ACPrice** [comment]
I've run into this issue as well. @kenwheeler Any plans to merge a/this fix soon?

**Comment by mdaxtman** [comment]
closed in favor of #159

**Pull request closed without merging**
