### PR TITLE
remove reserved goToSlide on carousel unmount

### LINKED ISSUE #550: Can't perform a React state update on an unmounted component
# Bugs and Questions

### Describe Your Environment

- What version of nuka-carousel are you using?
4.5.5
- What version of React are you using?
16.8.6
- What browser are you using?
Chrome
- What machine are you on?
Macbook

### Describe the Problem
Sometimes when navigating away from page with carousel, I receive the following error in console.  It appears that this might be an issue related to goToSlide, but it doesn't happen every time.
```
Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.

### PR DESCRIPTION
**Pull request by namuwikilover**
### Description
In my project, below error has occured when i moved to another page with the react router

```
index.js:652 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
in Carousel (created by Section1)
    in div (created by Context.Consumer)
    in StyledComponent (created by Section1__SliderWrapper)
    in Section1__SliderWrapper (created by Section1)
    in section (created by Context.Consumer)
    in StyledComponent (created by Section1__Section)
    in Section1__Section (created by Section1)
    in Section1 (created by StartupHomeContainer)
    in Unknown (created by StartupHomeContainer)
    in StartupHomeContainer (created by Context.Consumer)
    in Route


goToSlide | @ | index.js:652
-- | -- | --
...
```
So I've enrolled goToSlide in componentWillUnmount, and the error disappeared

Fixes #550  (issue)

#### Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)

### Checklist: (Feel free to delete this section upon completion)
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by namuwikilover** [comment]
Hmm....... I think, travis check is not related to my code...?? hmm...
https://benlimmer.com/2019/01/14/travis-ci-xvfb/

**Comment by paulathevalley** [comment]
@namuwikilover yes, you are correct! The failure is not related. `master` has been updated, so if you merge in `master`, travis should be running correctly.

**Comment by namuwikilover** [comment]
@paulathevalley pull request have been passed thanks to you. thank you!

**Comment by sarmeyer** [comment]
@namuwikilover I opened a new PR here with updated changes in an effort to fix this issue. https://github.com/FormidableLabs/nuka-carousel/pull/576

**Comment by namuwikilover** [comment]
> @namuwikilover I opened a new PR here with updated changes in an effort to fix this issue. #576
> 
> Would you mind reviewing and testing it out to see if it still solves the issue you're experiencing?

**Comment by namuwikilover** [comment]
@sarmeyer Looks good! thank you. I've tested this. there was no error!

**Comment by sarmeyer** [comment]
merged changes in PR #576

**Pull request closed without merging**
