### PR TITLE
avoiding deprecation warnings with createClass in React 15. Updating for v16.

### PR DESCRIPTION
**Pull request by jonkwheeler**
As the title states. I get a low priority warning in the console. Just wanted to clean it up.

```Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class```

I simply just updated the way `createClass` is used, with `createReactClass`, as told on https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.createclass

The current demo run should return no warnings in the console.

### CODE REVIEW

**Comment by o2dazone** [comment]
Looks like your PR contains a `package-lock.json` and `yarn.lock`, neither of which are present in the master branch. And the addition for `create-react-class` is not present in `package.json`. Was that intentional?

**Comment by jonkwheeler** [comment]
@o2dazone I was under the impression that lock files should be committed. If I'm mistaken, I'll remove and push. `create-react-class` is not necessary with React v15.5+. Should we import it as a fallback?

**Comment by jonkwheeler** [comment]
@o2dazone handled both points you made.

**Comment by o2dazone** [comment]
👍  unfortunately I don't have write acess. I too am waiting for this change for a project at work. Just wanted to make sure there weren't any hangups so maintainers can merge in ASAP :)

**Comment by jonkwheeler** [comment]
Who can merge this?

**Comment by kenwheeler** [comment]
Hey, gonna get this merged today, providing local stuff checks out

**Comment by ajb** [comment]
Eagerly awaiting this patch. Thanks to everyone involved ❤️

**Comment by kenwheeler** [comment]
@jonkwheeler thanks dude, sorry about the wait, was out on vacay. sick last name btw.

**Comment by jonkwheeler** [comment]
@kenwheeler No worries. Thanks for the merge. Sick last name indeed.

**Pull request merged**
