### PR TITLE
Fix initial height

### LINKED ISSUE #202: setDimensions bug? ul.slider-list too tall after componentDidMount
My horizontal slider with all default props is too tall on first mount, and I think this is why:

* `componentWillMount -> setInitialDimensions` sets `ul.slider-list` and each `li.slider-slide` to zero width

* Then we come to `componentDidMount -> setDimensions`, where

* `firstSlide.style.height = 'auto';` allows the `li.slider-slide` to grow vertically 

* which is then measured to calculate the height of the slider 
`slideHeight = firstSlide.offsetHeight;`

**BUT**

* `li.firstSlide` is still zero width! So all of its content gets squeezed to minimal width, forcing it down and making it way too tall!

* A few lines later, `slideWidth` is properly calculated. 
`slideWidth = frame.offsetWidth / props.slidesToShow * props.slideWidth;`
But it's not applied to the DOM yet, so we still wouldnt be able to properly measure the `firstSlide.offsetHeight`

* Then `setState` triggers a render which applies the correct width to `ul.slider-list` and `li.slider-slide`, but the **wrong height** to `ul.slider-list`. 

* Then, if we're lucky enough to have mounted this component on first page load, we may have a `readystatechange` event trigger another `setDimensions` which will calculate the correct `firstSlide.offsetHeight`, this time because the correct `slideWidth` has already been applied to the DOM.

So basically `setDimensions` needs to run twice *after* mounting in order to get it right. And if I'm mounting this component in a SPA long after readystatechange has fired, it only runs once. Am I doing something wrong? Or is this a bug. I'm not sure what the fix should be because I'm afraid that fixing for my own case would break other configurations. Whatever the case, **the first slide needs to be given its final width in the DOM before its offsetHeight is measured.**

### PR DESCRIPTION
**Pull request by vyteniskuciauskas-home24**
Trying to fix initial height bug
This should fix the following reproducible issue: https://codesandbox.io/s/0qr88707wp

Closes #202 #457 #417 #103

### CODE REVIEW

**Comment by sarmeyer** [comment]
@vyteniskuciauskas-home24 Just finished testing this and it works great. Thanks for taking the time to submit this PR and doing the work of responding to the issues related. I'll cut a release with this fix in since it's such a needed bug fix!

**Comment by stefangordon** [comment]
Oh wow I have been watching some of those bugs for literally years - almost sad to see them go ;)

Thanks for this!

**Comment by IMFIL** [comment]
Do you know when the release will be live ?

**Comment by sarmeyer** [comment]
@IMFIL release 4.4.5 live today

**Comment by wereHamster** [comment]
I'm still seeing the issue, and it kindof went away when I set `width:100vw` on the slides. I didn't investigate much further.

**Comment by devedupereira** [comment]
I'm still fighting with this error too. @wereHamster your workaround doesn't work fine, sometimes the content inside slide go out from screen because this width setted.

**Comment by yyynnn** [comment]
Same here, height is still 0 when routes change (via browser history).

**Comment by flikQ** [comment]
Doesn't seem to be fixed for me

**Comment by aamorozov** [comment]
Looks like it is still an issue with `v4.4.7`

**Comment by SummitPatel** [comment]
Also still having this issue with `4.4.7`. 

Temporary fix was to wrap my `Review` component (i.e. the slides of the carousel) in a `div` with a height set: 

```
export const ReviewsCarousel = props => (
  <Carousel heightMode={"max"}>
    {props.reviews.length &&
      props.reviews.map((review, i) => {
        return (
          <div style={{ height: 200 }}>
            <Review
              key={i}
              content={review.attributes.review}
              rating={review.attributes.rating}
            />
          </div>
        );
      })}
  </Carousel>
);
```

**Comment by Blobson** [comment]
You can try this [workaround](https://github.com/FormidableLabs/nuka-carousel/issues/457#issuecomment-478349501) to set fixed height and aspect ratio.

**Comment by jibin2706** [comment]
Still having issues with height on initial render

**Pull request merged**
