### PR TITLE
Drop v4 support, cleanup repo

### LINKED ISSUE #920: [v6] Drop v4 support
Drop v4 support, which will involve condensing to a single `src` folder (instead of carrying around a `src-v*` _and_ a `src` folder.

### PR DESCRIPTION
**Pull request by gksander**
### Description

This PR drops v4 support and purges some unused code. This includes:

- Moving `src-v5` to `src` and dropping the old `src` folder.
- Cleaning up build scripts.
- Remove unused Jest test.
- Fixing storybook suite accordingly, removing v4 carousel instances.

Fixes #920

### CODE REVIEW

**Comment by gksander** [comment]
Looks like I borked the cypress tests. Will patch that up next week.

**Comment by gksander** [comment]
Note on the UI review/tests: I added a slight change in the storybook layout since dropping v4, which has resulted in (I think) all of the stories having a minor diff in their layout.

**Comment by carlos-kelly** [comment]
@gksander I am seeing a lot of unsatisfied deps errors with `yarn check` is that just me?

```
error "use-latest#use-isomorphic-layout-effect#react@^16.8.0 || ^17.0.0" doesn't satisfy found match of "react@18.0.0"
info Found 26 warnings.
```

**Review by carlos-kelly — APPROVED** [review]
This is a good first step to getting some of the other infrastructure pieces in!

**Pull request merged**
